services:
  backend:
    build: ./backend
    environment:
      DB_USER: bpuser
      DB_PW: password
      DB_NAME: bpdb
      DB_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - bp_internal
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - bp_internal
  db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    networks:
      - bp_internal
    environment:
      POSTGRES_USER: bpuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bpdb

networks:
  bp_internal:
    external: false
